# Generated by Django 4.2.7 on 2025-12-28 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modelresponse',
            old_name='response',
            new_name='reponse',
        ),
    ]
