# Docker Compose for 3 Chat Bots
services:
  proxy:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

  frontend:
    build: ./frontend
    expose:
      - "8000"
    env_file:
      - .env
    environment:
      DEBUG: "false"

  backend:
    build: ./backend
    expose:
      - "8001"
    env_file:
      - .env
    environment:
      DEBUG: "false"
    volumes:
      - backend_db:/app/db.sqlite3

volumes:
  backend_db:
